SELECT
    MONTH(ch.START_DATE) MONTH
    , ch.CAR_ID
    , COUNT(*) RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
JOIN
    (SELECT 
        CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10' 
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5) cch
ON 
    ch.CAR_ID = cch.CAR_ID
WHERE 
    ch.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH(ch.START_DATE), ch.CAR_ID
ORDER BY 
    MONTH(ch.START_DATE), ch.CAR_ID DESC