SELECT hg.SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL FROM HR_EMPLOYEES he 
JOIN (
    SELECT 
        SUM(SCORE) SCORE
        , EMP_NO 
    FROM HR_GRADE 
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) hg ON he.EMP_NO = hg.EMP_NO