SELECT fp.CATEGORY, fp.PRICE AS MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
) t
ON fp.CATEGORY = t.CATEGORY
AND fp.PRICE = t.MAX_PRICE
ORDER BY MAX_PRICE DESC;
